steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']  # Jika kamu pakai proses build

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'ProjectBackendLibraryApp'     # Ganti dengan nama servicemu
      - '--source=.'               # Artinya deploy dari direktori saat ini
      - '--region=asia-southeast2' # Ganti dengan region yang kamu pakai
      - '--platform=managed'
      - '--allow-unauthenticated'


options:
  logging: CLOUD_LOGGING_ONLY