steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'project-backend-library-app'        
      - '--source=.'                  
      - '--region=asia-southeast2'   
      - '--platform=managed'
      - '--allow-unauthenticated'  

timeout: '1200s'  # Timeout build (20 menit)

options:
  logging: CLOUD_LOGGING_ONLY